server:
  port: 8888


spring:
    application:
      name: ConfigServer
    cloud:
      config:
        server:
          git:
            uri: https://github.com/codigorefinado/curso-spring-cloud
# Repositório privados podem ser acessados passando usuário e senha
# spring.cloud.config.server.git.username
# spring.cloud.config.server.git.password
# ou por ssh: spring.cloud.config.server.git.privateKey