spring:
  application:
    name: productservice

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@